pipeline {
    agent none
    stages {
        stage("Backend Stage") {
            agent {
                docker {
                    image 'maven:3.8.1-adoptopenjdk-11'
                }
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage("Frontend Stage") {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}